server:
  port: 8090

spring:
  application:
    name: relocation-backend

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        web: DEBUG